import { useMemo, useState, type FormEvent } from "react";
import {
  ArrowUpRight,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Instagram,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  Star,
  X,
} from "lucide-react";

type Service = { name: string; price: string };
type MenuGroup = { name: string; filter: string; items: Service[] };

const business = {
  name: "SAMMOHAK",
  phone: "+91 9119169110",
  whatsapp: "919119169110",
  address:
    "171/5, Sector-17, Haldighati Marg, Pratap Nagar, Jaipur - 302033, Rajasthan, India",
  instagram: "",
  reviews: "",
  maps: "",
};

const menu: MenuGroup[] = [
  { name: "Hair Care – Female", filter: "Hair", items: [["Hair Wash","₹300"],["Blow Dryer","₹300"],["Hair Wash and Blow Dryer","₹500"],["Hair Cut","₹600"],["Bob Cut","₹1000"],["Hair Straightening / Curls / Tongs","₹800"],["Deep Conditioning Wash","₹800"],["Fringe / Flick","₹300"],["Baby Girl Hair Cut","₹300"]].map(([name,price])=>({name,price})) },
  { name: "Hair Ritual", filter: "Hair", items: [["L'Oreal Hair Spa","₹1000"],["Milk Shake Cocktail Hair Spa","₹3000"],["Milk Shake Moisture Plus Ritual","₹2500"],["Milk Shake Argan Ritual","₹2500"],["Milk Shake Energizing Blend Ritual","₹2500"],["Milk Shake Integrity Nourishing Ritual","₹2500"],["Ola Plex Hair Treatment","₹3000"],["Anti Dandruff Treatment","₹2000"],["Oil Head Massage","₹600"]].map(([name,price])=>({name,price})) },
  { name: "Hair Textures", filter: "Hair", items: [["Keratin Treatment","Starting ₹3500"],["Smoothening Treatment","Starting ₹4000"],["Kerasmooth Treatment","Starting ₹6000"],["Hair Botox","Starting ₹5000"]].map(([name,price])=>({name,price})) },
  { name: "Hair Colour", filter: "Hair", items: [["Root Touch-Up","₹1200"],["Global Hair Colour","Starting ₹3500"],["Balayage Hair Colour","Starting ₹4500"],["Highlights Hair Colour","Starting ₹5000"]].map(([name,price])=>({name,price})) },
  { name: "Hair – Male", filter: "Hair", items: [["Hair Cut","₹300"],["Baby Boy Cut","₹250"],["Beard Cut","₹200"],["Hair Styling","₹200"],["Shaving","₹200"],["Oil Head Massage","₹400"],["D-Tan","₹400"],["D-Tan & Cleanup","₹1500"],["Beard Colour","₹500"],["24K Gold Pack","₹1200"]].map(([name,price])=>({name,price})) },
  { name: "Skin", filter: "Skin", items: [["Lotus","₹700"],["O3","₹1000"],["D-Tan","₹400"],["Instant Skin Brightening Mask","₹1200"],["Brightening Algae Mask","₹600"],["Rebalancing Algae Mask","₹600"],["Rejuvenating Mask","₹600"]].map(([name,price])=>({name,price})) },
  { name: "Facial", filter: "Skin", items: [["Lotus Facial","₹1500"],["O3+ Facial","₹2000"],["Jeannot Instant Glow Facial","₹3000"],["Jeannot Brilliance White Facial","₹3000"],["Jeannot Hydra Boost Facial","₹2200"],["Jeannot Infinite Youth Facial","₹2500"],["Jeannot Shine Control Facial","₹3100"],["Urban Men's Facial","₹2000"],["O3 Meladerm Facial","₹2500"]].map(([name,price])=>({name,price})) },
  { name: "Beauty – Female", filter: "Beauty", items: [["Baby Polishing","₹3500"],["O3+ Body Polishing","₹4500"],["Bleach","₹500"],["Eyebrow","₹50"],["Upper Lip","₹50"],["Forehead","₹50"],["Face Wax","₹500"],["Side Locks","₹200"]].map(([name,price])=>({name,price})) },
  { name: "Pedicure", filter: "Nails", items: [["Classic Pedicure","₹600"],["Nourishment Pedicure","₹750"],["D-Tan Pedicure","₹800"],["Candle Therapy Pedicure","₹1000"],["Tangled Pedicure","₹1300"],["Classic Foot Massage","₹500"]].map(([name,price])=>({name,price})) },
  { name: "Manicure", filter: "Nails", items: [["Classic Manicure","₹500"],["Nourishment Manicure","₹650"],["D-Tan Manicure","₹700"],["Candle Therapy Manicure","₹800"],["Tangled Manicure","₹1000"]].map(([name,price])=>({name,price})) },
  { name: "Makeup", filter: "Makeup", items: [["Bridal · Air Brush","₹21000"],["Bridal · HD","₹18000"],["Bridal · Mineral","₹15000"],["Reception / Engagement · Air Brush","₹15000"],["Reception / Engagement · HD","₹12000"],["Reception / Engagement · Mineral","₹10000"],["Party · Air Brush","₹7000"],["Party · HD","₹5000"],["Party · Mineral","₹2500"],["Groom · Air Brush","₹5000"],["Groom · HD","₹4000"],["Groom · Mineral","₹3500"]].map(([name,price])=>({name,price})) },
  { name: "Nail Artistry", filter: "Nails", items: [["Hard Gel Extension","₹1200"],["Soft Gel Extension","₹900"],["Gel Nail Paint","₹500"],["Nail Extension Removal","₹300"],["Gel Paint Removal","₹300"],["Nail Ombre Art","₹500"],["Nail French Art","₹500"],["Matte Coat","₹200"],["Chrome","₹50 per nail"],["Foil Art","₹100 per nail"],["Miller Art","₹100 per finger"],["Sprinkle Glitter","₹100 per finger"]].map(([name,price])=>({name,price})) },
  { name: "Aesthetic", filter: "Aesthetic", items: [["Chemical Peel","₹3000"],["Hydra Facial","₹5000"],["Derma Roller","₹2000"],["Comedones Extraction","₹3000"],["Face Slimming","₹1000 per sitting"],["Acne Treatment","₹1000 per sitting"]].map(([name,price])=>({name,price})) },
  { name: "Eyelash Extensions", filter: "Lashes", items: [["Natural","₹2500"],["Hybrid","₹3500"],["Classic","₹3500"],["Volume","₹4000"],["Open Eye","₹4000"]].map(([name,price])=>({name,price})) },
];

const waxing = [
  ["Half Arms","₹100","₹200","—"],["Full Arms","₹200","₹400","—"],
  ["Half Leg","₹200","₹350","—"],["Full Leg","₹400","₹750","—"],
  ["Under Arms","₹100","₹150","₹250"],["Back & Front","₹450","₹800","₹1000"],
  ["Bikini","₹1250","₹1500","₹2000"],["Full Body","₹1200","₹2500","—"],
];
const gallery = [
  ["/images/sammohak-hero.jpg","Hair","The art of the finish"],
  ["/images/sammohak-bridal.jpg","Bridal","Your moment, made personal"],
  ["/images/sammohak-nails.jpg","Nails","Small details, lasting impression"],
  ["/images/sammohak-interior.jpg","Beauty","A quieter kind of luxury"],
];

function Logo({ light = false }: { light?: boolean }) {
  return <div className={`flex items-center gap-3 ${light ? "text-[#f5e9d6]" : "text-[#351b19]"}`}><div className="grid h-10 w-10 place-items-center rounded-full border border-[#d6b56d] font-serif text-xl">S</div><div><div className="font-serif text-xl tracking-[.22em]">SAMMOHAK</div><div className="text-[9px] tracking-[.35em] opacity-70">UNISEX SALON</div></div></div>;
}

function BookingModal({ service, onClose }: { service: string; onClose: () => void }) {
  const [form, setForm] = useState({ name: "", phone: "", service, date: "", time: "", message: "" });
  const submit = (e: FormEvent) => {
    e.preventDefault();
    if (!form.name || !form.phone || !form.service || !form.date || !form.time) return;
    const text = `Hello SAMMOHAK Salon,\n\nI would like to book an appointment.\n\nName: ${form.name}\nPhone: ${form.phone}\nService: ${form.service}\nPreferred Date: ${form.date}\nPreferred Time: ${form.time}\nMessage: ${form.message}\n\nThank you.`;
    window.open(`https://wa.me/${business.whatsapp}?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer");
  };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#211311]/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="booking-title"><div className="max-h-[92vh] w-full max-w-xl overflow-auto bg-[#fbf5ed] p-6 shadow-2xl sm:p-10"><div className="mb-8 flex items-start justify-between"><div><p className="mb-2 text-[10px] uppercase tracking-[.3em] text-[#9a7042]">Private appointment request</p><h2 id="booking-title" className="font-serif text-4xl text-[#351b19]">Let’s make time for you.</h2></div><button onClick={onClose} aria-label="Close booking"><X /></button></div><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{[["name","Name"],["phone","Phone"],["date","Preferred Date"],["time","Preferred Time"]].map(([key,label])=><label key={key} className="text-xs uppercase tracking-[.14em] text-[#795d52]">{label}<input required value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} type={key==="date"?"date":key==="time"?"time":"text"} className="mt-2 w-full border-b border-[#cbb49b] bg-transparent px-0 py-3 text-base normal-case tracking-normal outline-none focus:border-[#9a7042]" /></label>)}<label className="text-xs uppercase tracking-[.14em] text-[#795d52] sm:col-span-2">Service<select required value={form.service} onChange={e=>setForm({...form,service:e.target.value})} className="mt-2 w-full border-b border-[#cbb49b] bg-transparent py-3 text-base normal-case tracking-normal outline-none">{menu.flatMap(g=>g.items.map(i=><option key={`${g.name}-${i.name}`}>{g.name} · {i.name}</option>))}</select></label><label className="text-xs uppercase tracking-[.14em] text-[#795d52] sm:col-span-2">Message<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows={3} className="mt-2 w-full border-b border-[#cbb49b] bg-transparent py-3 text-base normal-case tracking-normal outline-none" /></label><button className="mt-4 flex items-center justify-center gap-3 bg-[#4a2824] px-5 py-4 text-xs uppercase tracking-[.2em] text-[#f8f1e7] transition hover:bg-[#6a3831] sm:col-span-2">Request Appointment <ArrowUpRight size={16}/></button></form></div></div>;
}

export function SammohakHomepage() {
  const [booking, setBooking] = useState(false);
  const [selectedService, setSelectedService] = useState("");
  const [filter, setFilter] = useState("All");
  const [openGroup, setOpenGroup] = useState("Hair Care – Female");
  const [mobileNav, setMobileNav] = useState(false);
  const [lightbox, setLightbox] = useState<number | null>(null);
  const visible = useMemo(() => filter === "All" ? menu : menu.filter(g => g.filter === filter), [filter]);
  const book = (service = "") => { setSelectedService(service); setBooking(true); };
  const wa = () => window.open(`https://wa.me/${business.whatsapp}`, "_blank", "noopener,noreferrer");
  return <div className="min-h-screen overflow-x-hidden bg-[#fbf5ed] text-[#351b19] font-['DM_Sans',sans-serif] selection:bg-[#d6b56d] selection:text-[#351b19]">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-[#351b19]/85 px-5 py-4 text-[#f8f1e7] backdrop-blur-md sm:px-10"><div className="mx-auto flex max-w-[1400px] items-center justify-between"><a href="#home" aria-label="SAMMOHAK home"><Logo light/></a><nav className="hidden items-center gap-7 text-[10px] uppercase tracking-[.2em] lg:flex">{["Services","Menu","Gallery","About","Reviews","Contact"].map(x=><a key={x} href={`#${x.toLowerCase()}`} className="opacity-75 transition hover:text-[#e8d29a] hover:opacity-100">{x}</a>)}</nav><button onClick={()=>book()} className="hidden border border-[#d6b56d] px-5 py-3 text-[10px] uppercase tracking-[.2em] text-[#e8d29a] transition hover:bg-[#d6b56d] hover:text-[#351b19] sm:block">Book Appointment</button><button onClick={()=>setMobileNav(!mobileNav)} className="lg:hidden" aria-label="Toggle menu" aria-expanded={mobileNav}>{mobileNav?<X/>:<Menu/>}</button></div>{mobileNav&&<nav className="grid gap-5 px-2 pb-4 pt-6 text-sm uppercase tracking-[.2em] lg:hidden">{["Services","Menu","Gallery","About","Reviews","Contact"].map(x=><a onClick={()=>setMobileNav(false)} key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}<button onClick={()=>{setMobileNav(false);book()}} className="w-fit border border-[#d6b56d] px-4 py-3 text-[#e8d29a]">Book Appointment</button></nav>}</header>
    <main id="home">
      <section className="relative flex min-h-[760px] items-end overflow-hidden bg-[#351b19] px-5 pb-24 pt-32 text-[#f8f1e7] sm:px-10 lg:min-h-[850px] lg:pb-28"><img src={gallery[0][0]} alt="Editorial hair styling at SAMMOHAK" width="1200" height="1500" className="absolute inset-0 h-full w-full object-cover opacity-60 mix-blend-screen"/><div className="absolute inset-0 bg-gradient-to-r from-[#351b19] via-[#351b19]/50 to-transparent"/><div className="relative mx-auto w-full max-w-[1400px]"><p className="mb-6 text-[10px] uppercase tracking-[.38em] text-[#e8d29a]">Pratap Nagar · Jaipur</p><h1 className="serif max-w-3xl text-7xl leading-[.82] sm:text-9xl">Beauty,<br/><i>with a point of view.</i></h1><p className="mt-8 max-w-md text-sm leading-7 text-[#f8f1e7]/75">Where beauty meets artistry, and every detail is designed around you.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>book()} className="bg-[#d6b56d] px-6 py-4 text-[10px] uppercase tracking-[.2em] text-[#351b19] transition hover:bg-[#e8d29a]">Book an appointment</button><a href="#services" className="border border-[#f8f1e7]/50 px-6 py-4 text-[10px] uppercase tracking-[.2em]">Explore services</a></div></div><div className="absolute bottom-9 right-10 hidden items-center gap-3 text-[10px] uppercase tracking-[.25em] text-[#e8d29a] md:flex"><span className="h-px w-12 bg-[#d6b56d]"/>Scroll to discover</div></section>
      <section className="border-b border-[#d8c9b9] bg-[#f4eadf] px-5 py-10 sm:px-10" aria-label="Salon rating"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-8 md:flex-row md:items-center"><div className="flex items-center gap-5"><span className="serif text-6xl text-[#9a7042]">4.9</span><div><div className="mb-1 flex gap-1 text-[#9a7042]">{[1,2,3,4,5].map(i=><Star key={i} size={13} fill="currentColor"/>)}</div><p className="text-[10px] uppercase tracking-[.2em]">495 Reviews</p></div></div><p className="max-w-sm text-sm leading-6 text-[#795d52]">Trusted by hundreds of clients in Jaipur.<br/>A refined beauty destination for every kind of self-expression.</p><button onClick={()=>business.reviews?window.open(business.reviews,"_blank","noopener,noreferrer"):alert("Reviews link coming soon.")} className="flex items-center gap-2 text-xs uppercase tracking-[.16em] underline underline-offset-8">Read our reviews <ArrowUpRight size={15}/></button></div></section>
      <section id="services" className="mx-auto max-w-[1400px] px-5 py-24 sm:px-10 lg:py-32"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#9a7042]">The SAMMOHAK edit</p><h2 className="serif text-6xl leading-none sm:text-8xl">Beauty,<br/><i>styled your way.</i></h2></div><p className="max-w-sm text-sm leading-7 text-[#795d52]">From everyday grooming to unforgettable bridal moments, discover a complete range of salon experiences.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Hair","Cuts, styling, colour and treatments.","sammohak-hero.jpg"],["Skin & Facial","Facials, skin rituals and treatments.","sammohak-interior.jpg"],["Makeup","Bridal, reception, engagement, party and groom.","sammohak-bridal.jpg"],["Nails","Manicure, pedicure, gel extensions and artistry.","sammohak-nails.jpg"]].map(([title,desc,img],i)=><article key={title} className={`group relative overflow-hidden ${i===0?"lg:col-span-2 lg:row-span-2":""} min-h-[260px] bg-[#4a2824]`}><img src={`/images/${img}`} alt={`${title} services at SAMMOHAK`} width="800" height="1000" loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-75 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#351b19] via-transparent to-transparent"/><div className="relative flex h-full min-h-[260px] flex-col justify-end p-6 text-[#f8f1e7]"><p className="text-[10px] uppercase tracking-[.25em] text-[#e8d29a]">0{i+1}</p><h3 className="serif mt-2 text-4xl">{title}</h3><p className="mt-2 max-w-xs text-xs leading-5 text-white/70">{desc}</p><button onClick={()=>document.getElementById("menu")?.scrollIntoView()} className="mt-5 flex w-fit items-center gap-2 text-[10px] uppercase tracking-[.2em]">Explore <ArrowUpRight size={14}/></button></div></article>)}</div></section>
      <section className="bg-[#4a2824] px-5 py-24 text-[#f8f1e7] sm:px-10 lg:py-32"><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#e8d29a]">Curated for you</p><h2 className="serif text-6xl leading-[.9] sm:text-8xl">Signature<br/><i>experiences.</i></h2><p className="mt-7 max-w-sm text-sm leading-7 text-[#f8f1e7]/65">A considered edit of the treatments our artists love to create.</p></div><div className="grid border-t border-[#d6b56d]/30">{[["Keratin Treatment","A smoother, softer silhouette.","Starting ₹3500"],["Jeannot Hydra Boost Facial","A replenishing ritual for luminous skin.","₹2200"],["Bridal Makeup · Air Brush","Your most photographed day, perfected.","₹21000"],["Hard Gel Extension","Sculpted length with a polished finish.","₹1200"]].map(([n,d,p])=><div key={n} className="flex items-center justify-between gap-4 border-b border-[#d6b56d]/30 py-6"><div><h3 className="serif text-2xl">{n}</h3><p className="mt-1 text-xs text-[#f8f1e7]/55">{d}</p></div><div className="text-right"><p className="text-sm text-[#e8d29a]">{p}</p><button onClick={()=>book(n)} className="mt-2 text-[10px] uppercase tracking-[.15em] underline underline-offset-4">Book</button></div></div>)}</div></div></section>
      <section id="menu" className="mx-auto max-w-[1400px] px-5 py-24 sm:px-10 lg:py-32"><div className="mb-10"><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#9a7042]">The full menu</p><h2 className="serif text-6xl sm:text-8xl">A menu of<br/><i>possibilities.</i></h2></div><div className="mb-8 flex gap-2 overflow-x-auto pb-3">{["All","Hair","Skin","Beauty","Nails","Makeup","Aesthetic","Lashes"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`whitespace-nowrap border px-4 py-3 text-[10px] uppercase tracking-[.17em] transition ${filter===x?"border-[#4a2824] bg-[#4a2824] text-[#f8f1e7]":"border-[#cbb49b] text-[#795d52]"}`}>{x}</button>)}</div><div className="grid gap-3 lg:grid-cols-[260px_1fr]"><div className="hidden border-r border-[#d8c9b9] pr-8 lg:block">{visible.map(g=><button key={g.name} onClick={()=>setOpenGroup(g.name)} className={`block w-full border-b border-[#e3d7c9] py-4 text-left text-xs ${openGroup===g.name?"font-semibold text-[#9a7042]":"text-[#795d52]"}`}>{g.name}<ChevronRight className="float-right" size={15}/></button>)}</div><div className="grid gap-3 sm:grid-cols-2">{visible.filter(g=>g.name===openGroup||filter!=="All").flatMap(g=>g.items.map(item=><div key={`${g.name}-${item.name}`} className="flex items-center justify-between gap-3 border-b border-[#e3d7c9] py-4"><div><p className="text-[9px] uppercase tracking-[.18em] text-[#9a7042]">{g.name}</p><h3 className="mt-1 text-sm">{item.name}</h3></div><div className="flex items-center gap-4"><span className="whitespace-nowrap text-sm text-[#795d52]">{item.price}</span><button onClick={()=>book(`${g.name} · ${item.name}`)} className="hidden text-[10px] uppercase tracking-[.12em] text-[#9a7042] underline underline-offset-4 sm:block">Book</button></div></div>))}</div></div><p className="mt-10 border-l-2 border-[#d6b56d] pl-4 text-xs italic text-[#795d52]">Accessories / Jewels / Rhinestones are chargeable separately. Toe Nail Charges are same as above.</p></section>
      <section className="bg-[#efe1d3] px-5 py-20 sm:px-10"><div className="mx-auto max-w-[1400px]"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#9a7042]">Waxing menu</p><h2 className="serif text-5xl sm:text-7xl">Smoothly<br/><i>considered.</i></h2></div><p className="max-w-xs text-xs leading-6 text-[#795d52]">Choose your preferred finish. Prices are listed by treatment.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-[#bda990] text-[10px] uppercase tracking-[.2em] text-[#9a7042]"><th className="py-4">Service</th><th>Normal</th><th>Rica</th><th>Peel-off</th></tr></thead><tbody>{waxing.map(row=><tr key={row[0]} className="border-b border-[#d8c9b9]"><td className="py-4">{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td></tr>)}</tbody></table></div></div></section>
      <section id="about" className="grid bg-[#351b19] text-[#f8f1e7] lg:grid-cols-2"><div className="min-h-[500px] bg-cover bg-center" style={{backgroundImage:`url(${gallery[3][0]})`}}/><div className="flex items-center px-6 py-20 sm:px-16 lg:px-20"><div><p className="mb-5 text-[10px] uppercase tracking-[.3em] text-[#e8d29a]">A destination in Jaipur</p><h2 className="serif text-6xl leading-[.9] sm:text-8xl">Where elegance<br/><i>meets perfection.</i></h2><p className="mt-8 max-w-md text-sm leading-7 text-[#f8f1e7]/65">SAMMOHAK Unisex Salon brings together hair artistry, beauty, skincare, makeup and modern grooming in one refined destination in Jaipur.</p><div className="mt-10 flex items-center gap-4 text-xs uppercase tracking-[.16em]"><span className="h-px w-12 bg-[#d6b56d]"/>Elegance · Style · Perfection</div></div></div></section>
      <section id="gallery" className="mx-auto max-w-[1400px] px-5 py-24 sm:px-10 lg:py-32"><div className="mb-12 flex items-end justify-between"><div><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#9a7042]">The visual diary</p><h2 className="serif text-6xl sm:text-8xl">The SAMMOHAK<br/><i>point of view.</i></h2></div><span className="hidden text-xs text-[#795d52] sm:block">Selected studio stories / 01—04</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.map(([src,cat,caption],i)=><button key={src} onClick={()=>setLightbox(i)} className={`group relative overflow-hidden text-left ${i===1?"md:mt-16":i===2?"md:-mt-8":""}`}><img src={src} alt={caption} width="800" height="1067" loading="lazy" className="aspect-[3/4] w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#351b19]/80 to-transparent p-4 pt-14 text-[#f8f1e7]"><p className="text-[9px] uppercase tracking-[.2em] text-[#e8d29a]">{cat}</p><p className="serif mt-1 text-xl">{caption}</p></div></button>)}</div></section>
      <section id="reviews" className="border-y border-[#d8c9b9] bg-[#f4eadf] px-5 py-20 text-center sm:px-10"><p className="text-[10px] uppercase tracking-[.3em] text-[#9a7042]">What Jaipur says</p><div className="mx-auto mt-5 flex max-w-xl flex-col items-center"><div className="serif text-8xl text-[#9a7042]">4.9</div><div className="my-2 flex gap-1 text-[#9a7042]">{[1,2,3,4,5].map(i=><Star key={i} size={17} fill="currentColor"/>)}</div><p className="mt-2 text-sm">Rated 4.9/5 by 495 customers</p><button onClick={()=>business.reviews?window.open(business.reviews,"_blank","noopener,noreferrer"):alert("Google Reviews link coming soon.")} className="mt-8 border border-[#4a2824] px-6 py-4 text-[10px] uppercase tracking-[.2em]">Read our Google reviews <ArrowUpRight className="ml-2 inline" size={14}/></button></div></section>
      <section id="contact" className="bg-[#4a2824] px-5 py-24 text-[#f8f1e7] sm:px-10 lg:py-32"><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-[1fr_.7fr]"><div><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#e8d29a]">Come find us</p><h2 className="serif text-6xl leading-none sm:text-8xl">Your chair<br/><i>is waiting.</i></h2><p className="mt-9 max-w-sm text-sm leading-7 text-[#f8f1e7]/65">{business.address}</p><div className="mt-7 flex flex-wrap gap-3"><a href={`tel:${business.phone}`} className="flex items-center gap-2 border border-[#f8f1e7]/30 px-5 py-3 text-[10px] uppercase tracking-[.15em]"><Phone size={14}/>Call salon</a><button onClick={wa} className="flex items-center gap-2 border border-[#d6b56d] px-5 py-3 text-[10px] uppercase tracking-[.15em] text-[#e8d29a]"><MessageCircle size={14}/>WhatsApp</button><button onClick={()=>business.maps?window.open(business.maps,"_blank","noopener,noreferrer"):alert("Directions link coming soon.")} className="flex items-center gap-2 border border-[#f8f1e7]/30 px-5 py-3 text-[10px] uppercase tracking-[.15em]"><MapPin size={14}/>Get directions</button></div></div><div className="flex items-end justify-start lg:justify-end"><div className="border-l border-[#d6b56d]/50 pl-7"><p className="text-[10px] uppercase tracking-[.25em] text-[#e8d29a]">Appointments</p><a href={`tel:${business.phone}`} className="serif mt-3 block text-3xl sm:text-4xl">{business.phone}</a><p className="mt-5 text-xs text-[#f8f1e7]/55">For bookings, enquiries and bridal consultations.</p></div></div></div></section>
    </main>
    <footer className="bg-[#351b19] px-5 py-12 text-[#f8f1e7] sm:px-10"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-8 md:flex-row md:items-end"><div><Logo light/><p className="mt-5 text-xs text-[#f8f1e7]/45">Elegance · Style · Perfection</p></div><div className="flex flex-wrap gap-5 text-[10px] uppercase tracking-[.15em] text-[#f8f1e7]/60"><a href="#services">Services</a><a href="#menu">Menu</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a><button onClick={()=>business.instagram?window.open(business.instagram,"_blank","noopener,noreferrer"):alert("Instagram link coming soon.")} aria-label="Instagram link unavailable until the official handle is provided"><Instagram size={14}/></button></div><p className="text-[10px] text-[#f8f1e7]/35">© SAMMOHAK Unisex Salon</p></div></footer>
    <div className="fixed bottom-0 inset-x-0 z-30 grid grid-cols-3 border-t border-[#d6b56d]/30 bg-[#351b19] text-[#f8f1e7] sm:hidden"><a href={`tel:${business.phone}`} className="flex items-center justify-center gap-2 py-4 text-[10px] uppercase tracking-[.15em]"><Phone size={14}/>Call</a><button onClick={wa} className="flex items-center justify-center gap-2 border-x border-[#d6b56d]/30 py-4 text-[10px] uppercase tracking-[.15em]"><MessageCircle size={14}/>WhatsApp</button><button onClick={()=>book()} className="flex items-center justify-center gap-2 bg-[#d6b56d] py-4 text-[10px] uppercase tracking-[.15em] text-[#351b19]"><CalendarDays size={14}/>Book</button></div>
    {booking&&<BookingModal service={selectedService} onClose={()=>setBooking(false)}/>}
    {lightbox!==null&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#211311]/90 p-5" onClick={()=>setLightbox(null)} role="dialog" aria-modal="true" aria-label="Gallery image"><button className="absolute right-5 top-5 text-[#f8f1e7]" aria-label="Close gallery"><X/></button><img src={gallery[lightbox][0]} alt={gallery[lightbox][2]} width="1200" height="1600" className="max-h-[85vh] max-w-[90vw] object-contain" onClick={e=>e.stopPropagation()}/><button onClick={e=>{e.stopPropagation();setLightbox((lightbox+gallery.length-1)%gallery.length)}} className="absolute left-4 text-[#f8f1e7]" aria-label="Previous image"><ChevronLeft size={30}/></button><button onClick={e=>{e.stopPropagation();setLightbox((lightbox+1)%gallery.length)}} className="absolute right-4 text-[#f8f1e7]" aria-label="Next image"><ChevronRight size={30}/></button></div>}
  </div>;
}

export default SammohakHomepage;